services:
  db:
    image: flashbots/builder-hub-db
    build:
      context: ../.
      dockerfile: docker/database/Dockerfile
    ports:
      - 127.0.0.1:5432:5432
    environment:
      PGUSER: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 5
      start_period: 2s
      timeout: 5s

  web:
    image: flashbots/builder-hub
    build:
      context: ../.
      dockerfile: docker/httpserver/Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    links:
      - "db:database"
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
      - 127.0.0.1:8082:8082
      - 127.0.0.1:8090:8090
    environment:
      MOCK_SECRETS: true
      POSTGRES_DSN: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
      LISTEN_ADDR: "0.0.0.0:8080"
      ADMIN_ADDR: "0.0.0.0:8081"
      INTERNAL_ADDR: "0.0.0.0:8082"
      METRICS_ADDR: "0.0.0.0:8090"
      DISABLE_ADMIN_AUTH: "1" # local dev only; do not use in production

  proxy:
    image: flashbots/builder-hub-mock-proxy
    links:
      - "web:web"
    ports:
      - 127.0.0.1:8888:8888
    environment:
      TARGET: "http://web:8080"
